export interface EmojiEntry {
  emoji: string;
  name: string;
  keywords: string[];
}

export interface EmojiCategory {
  id: string;
  label: string;
  icon: string;
  emojis: EmojiEntry[];
}

export const EMOJI_CATEGORIES: EmojiCategory[] = [
  {
    id: 'animals',
    label: 'Animals',
    icon: '🐾',
    emojis: [
      { emoji: '🐶', name: 'dog', keywords: ['puppy', 'pet', 'animal'] },
      { emoji: '🐱', name: 'cat', keywords: ['kitten', 'pet', 'animal'] },
      { emoji: '🐭', name: 'mouse', keywords: ['rodent', 'animal'] },
      { emoji: '🐹', name: 'hamster', keywords: ['pet', 'rodent'] },
      { emoji: '🐰', name: 'rabbit', keywords: ['bunny', 'pet'] },
      { emoji: '🦊', name: 'fox', keywords: ['wild', 'nature'] },
      { emoji: '🐻', name: 'bear', keywords: ['wild', 'grizzly'] },
      { emoji: '🐼', name: 'panda', keywords: ['bear', 'bamboo'] },
      { emoji: '🦁', name: 'lion', keywords: ['king', 'wild', 'safari'] },
      { emoji: '🐯', name: 'tiger', keywords: ['cat', 'wild', 'stripes'] },
      { emoji: '🦅', name: 'eagle', keywords: ['bird', 'fly', 'freedom'] },
      { emoji: '🦉', name: 'owl', keywords: ['bird', 'wisdom', 'night'] },
      { emoji: '🦋', name: 'butterfly', keywords: ['insect', 'nature', 'wings'] },
      { emoji: '🐝', name: 'bee', keywords: ['honey', 'insect', 'busy', 'worker'] },
    ],
  },
  {
    id: 'people',
    label: 'People & Activities',
    icon: '👤',
    emojis: [
      { emoji: '😀', name: 'grinning face', keywords: ['smile', 'happy', 'face'] },
      { emoji: '😊', name: 'smiling face', keywords: ['blush', 'warm', 'friendly'] },
      { emoji: '😎', name: 'cool face', keywords: ['sunglasses', 'awesome', 'chill'] },
      { emoji: '🤓', name: 'nerd face', keywords: ['geek', 'glasses', 'smart', 'study'] },
      { emoji: '🤔', name: 'thinking face', keywords: ['ponder', 'consider', 'idea'] },
      { emoji: '🥳', name: 'party face', keywords: ['celebrate', 'birthday', 'fun'] },
      { emoji: '😴', name: 'sleeping face', keywords: ['sleep', 'tired', 'rest', 'bed'] },
      { emoji: '👨‍💻', name: 'man technologist', keywords: ['coder', 'developer', 'software', 'laptop'] },
      { emoji: '👩‍💻', name: 'woman technologist', keywords: ['coder', 'engineer', 'developer', 'tech'] },
      { emoji: '🧑‍🎨', name: 'artist', keywords: ['painter', 'creative', 'art', 'design'] },
      { emoji: '🧑‍🔬', name: 'scientist', keywords: ['research', 'lab', 'experiment', 'chemistry'] },
      { emoji: '🧑‍🚀', name: 'astronaut', keywords: ['space', 'cosmonaut', 'rocket'] },
      { emoji: '🏃', name: 'runner', keywords: ['running', 'exercise', 'sprint', 'fitness'] },
      { emoji: '🚴', name: 'cyclist', keywords: ['bike', 'cycling', 'bicycle', 'sports'] },
      { emoji: '🏊', name: 'swimmer', keywords: ['swim', 'water', 'pool', 'sports'] },
      { emoji: '🧘', name: 'person meditating', keywords: ['meditation', 'yoga', 'mindful', 'zen'] },
      { emoji: '🧗', name: 'climber', keywords: ['climbing', 'rock', 'boulder', 'adventure'] },
      { emoji: '🤝', name: 'handshake', keywords: ['agreement', 'deal', 'partnership', 'team'] },
      { emoji: '👏', name: 'clapping hands', keywords: ['applause', 'praise', 'bravo'] },
      { emoji: '🙌', name: 'raising hands', keywords: ['celebration', 'high five', 'hooray'] },
      { emoji: '💪', name: 'flexed biceps', keywords: ['strong', 'muscle', 'workout', 'power'] },
      { emoji: '🧠', name: 'brain', keywords: ['mind', 'intellect', 'thinking', 'psychology'] },
    ],
  },
  {
    id: 'objects',
    label: 'Objects & Tech',
    icon: '💡',
    emojis: [
      { emoji: '💻', name: 'laptop', keywords: ['computer', 'macbook', 'work', 'code'] },
      { emoji: '🖥️', name: 'desktop computer', keywords: ['pc', 'monitor', 'screen', 'workstation'] },
      { emoji: '🖨️', name: 'printer', keywords: ['print', 'office', 'paper', 'scan'] },
      { emoji: '⌨️', name: 'keyboard', keywords: ['typing', 'keys', 'input', 'tech'] },
      { emoji: '🖱️', name: 'computer mouse', keywords: ['click', 'pointer', 'hardware'] },
      { emoji: '💽', name: 'computer disk', keywords: ['minidisc', 'storage', 'data'] },
      { emoji: '💾', name: 'floppy disk', keywords: ['save', 'diskette', 'storage', 'legacy'] },
      { emoji: '💿', name: 'optical disk', keywords: ['cd', 'disc', 'music', 'album'] },
      { emoji: '📀', name: 'dvd', keywords: ['movie', 'disc', 'video', 'media'] },
      { emoji: '📼', name: 'videocassette', keywords: ['vhs', 'tape', 'retro', 'recording'] },
      { emoji: '📱', name: 'mobile phone', keywords: ['iphone', 'smartphone', 'call', 'app'] },
      { emoji: '📲', name: 'phone with arrow', keywords: ['mobile', 'call', 'incoming', 'notification'] },
      { emoji: '☎️', name: 'telephone', keywords: ['landline', 'phone', 'contact'] },
      { emoji: '📞', name: 'telephone receiver', keywords: ['call', 'handset', 'support'] },
      { emoji: '📟', name: 'pager', keywords: ['beeper', 'retro', 'communication'] },
      { emoji: '📠', name: 'fax machine', keywords: ['fax', 'document', 'office'] },
      { emoji: '🔋', name: 'battery', keywords: ['power', 'energy', 'charge', 'electric'] },
      { emoji: '🔌', name: 'electric plug', keywords: ['cable', 'power', 'socket', 'connection'] },
      { emoji: '🕹️', name: 'joystick', keywords: ['game', 'arcade', 'controller'] },
      { emoji: '🎮', name: 'video game', keywords: ['gaming', 'controller', 'playstation', 'xbox'] },
      { emoji: '📷', name: 'camera', keywords: ['photo', 'picture', 'photography', 'snap'] },
      { emoji: '📸', name: 'camera with flash', keywords: ['photo', 'snapshot', 'capture'] },
      { emoji: '📹', name: 'video camera', keywords: ['camcorder', 'film', 'record'] },
      { emoji: '🎥', name: 'movie camera', keywords: ['cinema', 'film', 'hollywood', 'shoot'] },
      { emoji: '📽️', name: 'film projector', keywords: ['movie', 'presentation', 'cinema'] },
      { emoji: '🎞️', name: 'film frames', keywords: ['cinema', 'strip', 'reel', 'movie'] },
      { emoji: '📻', name: 'radio', keywords: ['audio', 'broadcast', 'music', 'station'] },
      { emoji: '📺', name: 'television', keywords: ['tv', 'screen', 'broadcast', 'watch'] },
      { emoji: '🎙️', name: 'studio microphone', keywords: ['podcast', 'recording', 'audio', 'mic'] },
      { emoji: '🎚️', name: 'level slider', keywords: ['fader', 'audio', 'sound', 'volume'] },
      { emoji: '🎛️', name: 'control knobs', keywords: ['dials', 'settings', 'adjust', 'audio'] },
      { emoji: '⏱️', name: 'stopwatch', keywords: ['timer', 'seconds', 'speed', 'countdown'] },
      { emoji: '⏲️', name: 'timer clock', keywords: ['kitchen', 'countdown', 'alarm'] },
      { emoji: '⏰', name: 'alarm clock', keywords: ['wake', 'time', 'alert', 'morning'] },
      { emoji: '🕰️', name: 'mantelpiece clock', keywords: ['time', 'vintage', 'antique'] },
      { emoji: '⏳', name: 'hourglass not done', keywords: ['time', 'sand', 'pending', 'wait'] },
      { emoji: '⌛', name: 'hourglass done', keywords: ['time', 'expired', 'finished', 'sand'] },
      { emoji: '📡', name: 'satellite antenna', keywords: ['dish', 'broadcast', 'signal', 'comms'] },
      { emoji: '💡', name: 'light bulb', keywords: ['idea', 'creative', 'bright', 'solution'] },
      { emoji: '🔦', name: 'flashlight', keywords: ['torch', 'light', 'search', 'bright'] },
      { emoji: '🏮', name: 'red paper lantern', keywords: ['light', 'asian', 'festival'] },
      { emoji: '🪔', name: 'diya lamp', keywords: ['oil', 'light', 'festival', 'diwali'] },
      { emoji: '🕯️', name: 'candle', keywords: ['wax', 'light', 'flame', 'meditate'] },
      { emoji: '🧯', name: 'fire extinguisher', keywords: ['emergency', 'safety', 'extinguish'] },
      { emoji: '💸', name: 'money with wings', keywords: ['dollar', 'flying', 'spend', 'payment'] },
      { emoji: '💵', name: 'dollar banknote', keywords: ['cash', 'currency', 'money', 'bucks'] },
      { emoji: '💴', name: 'yen banknote', keywords: ['currency', 'japan', 'money'] },
      { emoji: '💶', name: 'euro banknote', keywords: ['currency', 'europe', 'money'] },
      { emoji: '💷', name: 'pound banknote', keywords: ['currency', 'uk', 'money'] },
      { emoji: '💰', name: 'money bag', keywords: ['wealth', 'rich', 'cash', 'reward'] },
      { emoji: '💳', name: 'credit card', keywords: ['payment', 'bank', 'visa', 'mastercard'] },
      { emoji: '💎', name: 'gem stone', keywords: ['diamond', 'jewel', 'precious', 'crystal'] },
      { emoji: '⚖️', name: 'balance scale', keywords: ['justice', 'law', 'legal', 'balance'] },
      { emoji: '🧰', name: 'toolbox', keywords: ['tools', 'kit', 'repair', 'hardware'] },
      { emoji: '🔧', name: 'wrench', keywords: ['tool', 'fix', 'maintain', 'settings'] },
      { emoji: '🔨', name: 'hammer', keywords: ['tool', 'build', 'construction', 'hit'] },
      { emoji: '⚒️', name: 'hammer and pick', keywords: ['tools', 'mining', 'build'] },
      { emoji: '🛠️', name: 'hammer and wrench', keywords: ['tools', 'craft', 'repair', 'settings'] },
      { emoji: '⛏️', name: 'pick', keywords: ['mining', 'rock', 'dig'] },
      { emoji: '🔩', name: 'nut and bolt', keywords: ['hardware', 'screw', 'fastener'] },
      { emoji: '⚙️', name: 'gear', keywords: ['cog', 'settings', 'system', 'preferences'] },
      { emoji: '🗜️', name: 'clamp', keywords: ['compress', 'vice', 'tool'] },
      { emoji: '🦯', name: 'white cane', keywords: ['accessibility', 'guide', 'vision'] },
      { emoji: '🔗', name: 'link', keywords: ['url', 'hyperlink', 'connection', 'web'] },
      { emoji: '⛓️', name: 'chains', keywords: ['metal', 'lock', 'linked'] },
      { emoji: '🪝', name: 'hook', keywords: ['catch', 'hang', 'fishing'] },
      { emoji: '🧲', name: 'magnet', keywords: ['attract', 'physics', 'pull'] },
      { emoji: '🪜', name: 'ladder', keywords: ['climb', 'stairs', 'level up'] },
      { emoji: '🪓', name: 'axe', keywords: ['chop', 'wood', 'lumber'] },
      { emoji: '🗡️', name: 'dagger', keywords: ['blade', 'knife', 'weapon'] },
      { emoji: '⚔️', name: 'crossed swords', keywords: ['battle', 'duel', 'fight'] },
      { emoji: '🛡️', name: 'shield', keywords: ['defense', 'security', 'protection', 'guard'] },
      { emoji: '🏹', name: 'bow and arrow', keywords: ['archery', 'target', 'aim'] },
      { emoji: '💣', name: 'bomb', keywords: ['explosive', 'blast', 'danger'] },
      { emoji: '🪃', name: 'boomerang', keywords: ['return', 'throw', 'australia'] },
      { emoji: '🏺', name: 'amphora', keywords: ['urn', 'jar', 'vase', 'pottery'] },
      { emoji: '🔮', name: 'crystal ball', keywords: ['fortune', 'magic', 'future', 'prediction'] },
      { emoji: '📿', name: 'prayer beads', keywords: ['necklace', 'religion', 'rosary'] },
      { emoji: '🧿', name: 'nazar amulet', keywords: ['evil eye', 'talisman', 'protection'] },
      { emoji: '💈', name: 'barber pole', keywords: ['haircut', 'salon', 'style'] },
      { emoji: '🔭', name: 'telescope', keywords: ['astronomy', 'stars', 'space', 'zoom'] },
      { emoji: '🔬', name: 'microscope', keywords: ['science', 'lab', 'biology', 'zoom'] },
      { emoji: '🕳️', name: 'hole', keywords: ['black hole', 'gap', 'depth'] },
      { emoji: '🩹', name: 'adhesive bandage', keywords: ['bandaid', 'heal', 'fix', 'injury'] },
      { emoji: '🩺', name: 'stethoscope', keywords: ['doctor', 'medical', 'health', 'clinic'] },
      { emoji: '💊', name: 'pill', keywords: ['medicine', 'capsule', 'health', 'pharmacy'] },
      { emoji: '💉', name: 'syringe', keywords: ['vaccine', 'injection', 'medical', 'needle'] },
      { emoji: '🩸', name: 'drop of blood', keywords: ['bleed', 'donation', 'test'] },
      { emoji: '🧬', name: 'dna', keywords: ['genetics', 'evolution', 'biology', 'science'] },
      { emoji: '🧪', name: 'test tube', keywords: ['chemistry', 'experiment', 'lab', 'potion'] },
      { emoji: '🧫', name: 'petri dish', keywords: ['bacteria', 'lab', 'culture', 'biology'] },
      { emoji: '🧹', name: 'broom', keywords: ['sweep', 'clean', 'tidy'] },
      { emoji: '🪠', name: 'plunger', keywords: ['toilet', 'plumbing', 'drain'] },
      { emoji: '🧺', name: 'basket', keywords: ['laundry', 'picnic', 'container'] },
      { emoji: '🧻', name: 'roll of paper', keywords: ['toilet paper', 'tissue', 'clean'] },
      { emoji: '🧼', name: 'soap', keywords: ['wash', 'clean', 'hygiene', 'bubbles'] },
      { emoji: '🧽', name: 'sponge', keywords: ['scrub', 'clean', 'absorb'] },
      { emoji: '🧴', name: 'lotion bottle', keywords: ['cream', 'soap', 'dispenser'] },
      { emoji: '🗝️', name: 'old key', keywords: ['vintage', 'antique', 'secret', 'password'] },
      { emoji: '🔑', name: 'key', keywords: ['lock', 'access', 'password', 'security'] },
      { emoji: '🔒', name: 'locked', keywords: ['secure', 'closed', 'private', 'lock'] },
      { emoji: '🔓', name: 'unlocked', keywords: ['open', 'public', 'access'] },
      { emoji: '🔏', name: 'lock with pen', keywords: ['privacy', 'signature', 'encrypt'] },
      { emoji: '🔐', name: 'lock with key', keywords: ['safe', 'security', 'auth'] },
      { emoji: '📦', name: 'package', keywords: ['parcel', 'box', 'delivery', 'shipping'] },
      { emoji: '📫', name: 'closed mailbox with raised flag', keywords: ['mail', 'letter', 'post'] },
      { emoji: '📪', name: 'closed mailbox with lowered flag', keywords: ['mail', 'postal'] },
      { emoji: '📬', name: 'open mailbox with raised flag', keywords: ['mail', 'delivery', 'inbox'] },
      { emoji: '📭', name: 'open mailbox with lowered flag', keywords: ['mail', 'empty'] },
      { emoji: '📮', name: 'postbox', keywords: ['mailbox', 'postal', 'letters'] },
      { emoji: '✉️', name: 'envelope', keywords: ['letter', 'mail', 'message', 'email'] },
      { emoji: '📧', name: 'e-mail', keywords: ['inbox', 'message', 'digital mail'] },
      { emoji: '📨', name: 'incoming envelope', keywords: ['received', 'email', 'letter'] },
      { emoji: '📩', name: 'envelope with arrow', keywords: ['send', 'delivery', 'dispatch'] },
      { emoji: '📤', name: 'outbox tray', keywords: ['sent', 'mail', 'upload'] },
      { emoji: '📥', name: 'inbox tray', keywords: ['receive', 'download', 'incoming'] },
      { emoji: '🏷️', name: 'label', keywords: ['tag', 'price', 'category', 'organize'] },
      { emoji: '🔖', name: 'bookmark', keywords: ['save', 'reading', 'marker'] },
      { emoji: '🧾', name: 'receipt', keywords: ['bill', 'invoice', 'expense', 'proof'] },
      { emoji: '📊', name: 'bar chart', keywords: ['graph', 'analytics', 'statistics', 'metrics'] },
      { emoji: '📈', name: 'chart increasing', keywords: ['growth', 'profit', 'trend', 'analytics'] },
      { emoji: '📉', name: 'chart decreasing', keywords: ['loss', 'drop', 'decline', 'metrics'] },
      { emoji: '📇', name: 'card index', keywords: ['contacts', 'directory', 'rolodex'] },
      { emoji: '📋', name: 'clipboard', keywords: ['tasks', 'checklist', 'copy', 'paste'] },
      { emoji: '📌', name: 'pushpin', keywords: ['pinned', 'notice', 'board', 'marker'] },
      { emoji: '📍', name: 'round pushpin', keywords: ['location', 'place', 'marker', 'map'] },
      { emoji: '📎', name: 'paperclip', keywords: ['attachment', 'office', 'attach'] },
      { emoji: '🖇️', name: 'linked paperclips', keywords: ['attachment', 'document', 'together'] },
      { emoji: '📏', name: 'straight ruler', keywords: ['measure', 'length', 'ruler'] },
      { emoji: '📐', name: 'triangular ruler', keywords: ['geometry', 'math', 'drawing'] },
      { emoji: '✂️', name: 'scissors', keywords: ['cut', 'trim', 'snip', 'edit'] },
      { emoji: '🗃️', name: 'card file box', keywords: ['archive', 'records', 'storage'] },
      { emoji: '🗄️', name: 'file cabinet', keywords: ['files', 'storage', 'office', 'archive'] },
      { emoji: '🗑️', name: 'wastebasket', keywords: ['trash', 'bin', 'delete', 'remove'] },
      { emoji: '📝', name: 'memo', keywords: ['note', 'writing', 'pencil', 'document'] },
      { emoji: '📄', name: 'page facing up', keywords: ['document', 'file', 'sheet', 'paper'] },
      { emoji: '📃', name: 'page with curl', keywords: ['document', 'note', 'paper'] },
      { emoji: '📑', name: 'bookmark tabs', keywords: ['index', 'tabs', 'organization'] },
      { emoji: '📒', name: 'ledger', keywords: ['yellow notebook', 'accounting', 'notes'] },
      { emoji: '📓', name: 'notebook', keywords: ['notes', 'journal', 'writing'] },
      { emoji: '📔', name: 'notebook with decorative cover', keywords: ['diary', 'journal'] },
      { emoji: '📕', name: 'closed book', keywords: ['reading', 'novel', 'textbook', 'red book'] },
      { emoji: '📖', name: 'open book', keywords: ['reading', 'learning', 'study', 'manual'] },
      { emoji: '📗', name: 'green book', keywords: ['study', 'reading', 'nature book'] },
      { emoji: '📘', name: 'blue book', keywords: ['guide', 'manual', 'handbook'] },
      { emoji: '📙', name: 'orange book', keywords: ['specs', 'documentation', 'textbook'] },
      { emoji: '📚', name: 'books', keywords: ['library', 'reading', 'literature', 'stack'] },
      { emoji: '✏️', name: 'pencil', keywords: ['write', 'sketch', 'draw', 'draft'] },
      { emoji: '🖋️', name: 'fountain pen', keywords: ['sign', 'signature', 'ink', 'writing'] },
      { emoji: '🖊️', name: 'pen', keywords: ['ballpoint', 'write', 'author', 'office'] },
      { emoji: '🖌️', name: 'paintbrush', keywords: ['art', 'paint', 'canvas', 'design'] },
      { emoji: '🖍️', name: 'crayon', keywords: ['drawing', 'color', 'kids'] },
      { emoji: '🎨', name: 'artist palette', keywords: ['colors', 'art', 'design', 'creativity'] },
      { emoji: '🧵', name: 'thread', keywords: ['spool', 'sewing', 'needle'] },
      { emoji: '🪡', name: 'sewing needle', keywords: ['stitch', 'tailor', 'thread'] },
      { emoji: '🧶', name: 'yarn', keywords: ['knit', 'crochet', 'wool'] },
      { emoji: '🪢', name: 'knot', keywords: ['rope', 'tie', 'secure'] },
      { emoji: '👓', name: 'glasses', keywords: ['spectacles', 'eyesight', 'reading'] },
      { emoji: '🕶️', name: 'sunglasses', keywords: ['shades', 'cool', 'summer'] },
      { emoji: '🥽', name: 'goggles', keywords: ['safety', 'swimming', 'lab', 'eye protection'] },
      { emoji: '🥼', name: 'lab coat', keywords: ['doctor', 'scientist', 'chemist'] },
      { emoji: '🦺', name: 'safety vest', keywords: ['construction', 'reflective', 'worker'] },
      { emoji: '👔', name: 'necktie', keywords: ['formal', 'suit', 'business', 'office'] },
      { emoji: '👕', name: 't-shirt', keywords: ['clothing', 'casual', 'shirt'] },
      { emoji: '💼', name: 'briefcase', keywords: ['work', 'portfolio', 'business', 'case'] },
      { emoji: '👜', name: 'handbag', keywords: ['purse', 'bag', 'fashion'] },
      { emoji: '🎒', name: 'backpack', keywords: ['school', 'bag', 'travel', 'commute'] },
      { emoji: '🧳', name: 'luggage', keywords: ['suitcase', 'travel', 'vacation', 'trip'] },
      { emoji: '👑', name: 'crown', keywords: ['king', 'queen', 'royal', 'vip'] },
      { emoji: '🧢', name: 'billed cap', keywords: ['hat', 'baseball', 'casual'] },
      { emoji: '🎩', name: 'top hat', keywords: ['formal', 'gentleman', 'magic'] },
      { emoji: '🎓', name: 'graduation cap', keywords: ['degree', 'school', 'university', 'education'] },
      { emoji: '🪖', name: 'military helmet', keywords: ['defense', 'army', 'armor'] },
      { emoji: '🏆', name: 'trophy', keywords: ['winner', 'prize', 'champion', 'first'] },
      { emoji: '🥇', name: '1st place medal', keywords: ['gold', 'first', 'winner', 'award'] },
      { emoji: '🥈', name: '2nd place medal', keywords: ['silver', 'second', 'runner up'] },
      { emoji: '🥉', name: '3rd place medal', keywords: ['bronze', 'third'] },
      { emoji: '🏅', name: 'sports medal', keywords: ['medal', 'achievement', 'honor'] },
      { emoji: '🎖️', name: 'military medal', keywords: ['honor', 'ribbon', 'hero'] },
      { emoji: '🎫', name: 'ticket', keywords: ['admission', 'pass', 'event', 'coupon'] },
      { emoji: '🎟️', name: 'admission tickets', keywords: ['cinema', 'concert', 'movie'] },
      { emoji: '🎪', name: 'circus tent', keywords: ['carnival', 'fair', 'show'] },
      { emoji: '🎭', name: 'performing arts', keywords: ['theater', 'masks', 'drama', 'acting'] },
      { emoji: '🎯', name: 'bullseye', keywords: ['target', 'goal', 'aim', 'focus'] },
      { emoji: '🎲', name: 'game die', keywords: ['dice', 'random', 'board game', 'roll'] },
      { emoji: '🧩', name: 'puzzle piece', keywords: ['jigsaw', 'problem', 'solve', 'logic'] },
      { emoji: '♟️', name: 'chess pawn', keywords: ['chess', 'strategy', 'game'] },
      { emoji: '🎳', name: 'bowling', keywords: ['strike', 'pins', 'ball'] },
      { emoji: '🎸', name: 'guitar', keywords: ['music', 'instrument', 'rock', 'strings'] },
      { emoji: '🎹', name: 'musical keyboard', keywords: ['piano', 'music', 'instrument'] },
      { emoji: '🎺', name: 'trumpet', keywords: ['brass', 'horn', 'music', 'jazz'] },
      { emoji: '🎻', name: 'violin', keywords: ['strings', 'classical', 'music'] },
      { emoji: '🥁', name: 'drum', keywords: ['beat', 'rhythm', 'percussion'] },
      { emoji: '🪘', name: 'long drum', keywords: ['bongo', 'djembe', 'rhythm'] },
      { emoji: '🔔', name: 'bell', keywords: ['notification', 'alert', 'ring', 'alarm'] },
      { emoji: '🔕', name: 'bell with slash', keywords: ['mute', 'silent', 'quiet'] },
    ],
  },
  {
    id: 'food_plants',
    label: 'Food & Plants',
    icon: '🌱',
    emojis: [
      { emoji: '🌱', name: 'seedling', keywords: ['sprout', 'plant', 'growth', 'green'] },
      { emoji: '🌿', name: 'herb', keywords: ['leaf', 'botanical', 'nature', 'tea'] },
      { emoji: '🍀', name: 'four leaf clover', keywords: ['luck', 'fortune', 'irish'] },
      { emoji: '☘️', name: 'shamrock', keywords: ['clover', 'plant', 'ireland'] },
      { emoji: '🎍', name: 'pine decoration', keywords: ['bamboo', 'japanese', 'plant'] },
      { emoji: '🪴', name: 'potted plant', keywords: ['houseplant', 'indoor', 'gardening'] },
      { emoji: '🌲', name: 'evergreen tree', keywords: ['pine', 'forest', 'nature', 'christmas'] },
      { emoji: '🌳', name: 'deciduous tree', keywords: ['tree', 'park', 'nature', 'oak'] },
      { emoji: '🌴', name: 'palm tree', keywords: ['tropical', 'beach', 'summer', 'island'] },
      { emoji: '🌵', name: 'cactus', keywords: ['desert', 'succulent', 'dry'] },
      { emoji: '🌾', name: 'sheaf of rice', keywords: ['grain', 'wheat', 'harvest'] },
      { emoji: '🌷', name: 'tulip', keywords: ['flower', 'spring', 'bloom'] },
      { emoji: '🌸', name: 'cherry blossom', keywords: ['sakura', 'flower', 'pink'] },
      { emoji: '🌹', name: 'rose', keywords: ['flower', 'red', 'romance'] },
      { emoji: '🌺', name: 'hibiscus', keywords: ['flower', 'tropical', 'floral'] },
      { emoji: '🌻', name: 'sunflower', keywords: ['flower', 'sun', 'summer', 'yellow'] },
      { emoji: '🌼', name: 'blossom', keywords: ['flower', 'daisy', 'yellow'] },
      { emoji: '💐', name: 'bouquet', keywords: ['flowers', 'gift', 'arrangement'] },
      { emoji: '🍄', name: 'mushroom', keywords: ['fungus', 'nature', 'forest'] },
      { emoji: '🍁', name: 'maple leaf', keywords: ['autumn', 'fall', 'canada'] },
      { emoji: '🍂', name: 'fallen leaf', keywords: ['autumn', 'leaves', 'season'] },
      { emoji: '🍃', name: 'leaf fluttering in wind', keywords: ['wind', 'breeze', 'green'] },
      { emoji: '🍏', name: 'green apple', keywords: ['fruit', 'fresh', 'healthy'] },
      { emoji: '🍎', name: 'red apple', keywords: ['fruit', 'teacher', 'sweet'] },
      { emoji: '🍐', name: 'pear', keywords: ['fruit', 'fresh', 'sweet'] },
      { emoji: '🍊', name: 'tangerine', keywords: ['orange', 'citrus', 'mandarin'] },
      { emoji: '🍋', name: 'lemon', keywords: ['sour', 'citrus', 'yellow'] },
      { emoji: '🍌', name: 'banana', keywords: ['fruit', 'potassium', 'yellow'] },
      { emoji: '🍉', name: 'watermelon', keywords: ['fruit', 'summer', 'slice'] },
      { emoji: '🍇', name: 'grapes', keywords: ['fruit', 'vine', 'wine'] },
      { emoji: '🍓', name: 'strawberry', keywords: ['berry', 'fruit', 'sweet'] },
      { emoji: '🫐', name: 'blueberries', keywords: ['berry', 'fruit', 'healthy'] },
      { emoji: '🍒', name: 'cherries', keywords: ['fruit', 'red', 'pair'] },
      { emoji: '🍑', name: 'peach', keywords: ['fruit', 'sweet', 'soft'] },
      { emoji: '🥭', name: 'mango', keywords: ['fruit', 'tropical', 'sweet'] },
      { emoji: '🍍', name: 'pineapple', keywords: ['fruit', 'tropical', 'aloha'] },
      { emoji: '🥥', name: 'coconut', keywords: ['tropical', 'palm', 'nut'] },
      { emoji: '🥑', name: 'avocado', keywords: ['food', 'guacamole', 'healthy'] },
      { emoji: '🍆', name: 'eggplant', keywords: ['aubergine', 'vegetable'] },
      { emoji: '🥕', name: 'carrot', keywords: ['vegetable', 'healthy', 'orange'] },
      { emoji: '🌽', name: 'ear of corn', keywords: ['maize', 'vegetable', 'farm'] },
      { emoji: '🌶️', name: 'hot pepper', keywords: ['spicy', 'chili', 'mexican'] },
      { emoji: '🥒', name: 'cucumber', keywords: ['pickle', 'vegetable', 'green'] },
      { emoji: '🥦', name: 'broccoli', keywords: ['vegetable', 'green', 'healthy'] },
      { emoji: '🥖', name: 'baguette bread', keywords: ['french', 'bakery', 'bread'] },
      { emoji: '🥐', name: 'croissant', keywords: ['pastry', 'bakery', 'breakfast'] },
      { emoji: '🍞', name: 'bread', keywords: ['loaf', 'toast', 'bakery'] },
      { emoji: '🧀', name: 'cheese wedge', keywords: ['dairy', 'cheddar', 'swiss'] },
      { emoji: '🍔', name: 'hamburger', keywords: ['burger', 'fast food', 'patty'] },
      { emoji: '🍟', name: 'french fries', keywords: ['fries', 'potatoes', 'fast food'] },
      { emoji: '🍕', name: 'pizza', keywords: ['slice', 'cheese', 'italian', 'dinner'] },
      { emoji: '☕', name: 'hot beverage', keywords: ['coffee', 'tea', 'morning', 'espresso', 'cafe'] },
    ],
  },
  {
    id: 'places_travel',
    label: 'Travel & Places',
    icon: '🚀',
    emojis: [
      { emoji: '🚗', name: 'automobile', keywords: ['car', 'drive', 'vehicle', 'commute'] },
      { emoji: '🚙', name: 'sport utility vehicle', keywords: ['suv', 'car', 'travel'] },
      { emoji: '🏎️', name: 'racing car', keywords: ['race', 'f1', 'speed', 'fast'] },
      { emoji: '🚕', name: 'taxi', keywords: ['cab', 'uber', 'transport'] },
      { emoji: '🚌', name: 'bus', keywords: ['transit', 'public transport', 'school bus'] },
      { emoji: '🚎', name: 'trolleybus', keywords: ['transit', 'bus', 'electric'] },
      { emoji: '🚑', name: 'ambulance', keywords: ['medical', 'emergency', 'paramedic'] },
      { emoji: '🚒', name: 'fire engine', keywords: ['firetruck', 'fire', 'emergency'] },
      { emoji: '🚓', name: 'police car', keywords: ['cop', 'security', 'patrol'] },
      { emoji: '🚜', name: 'tractor', keywords: ['farm', 'agriculture', 'machine'] },
      { emoji: '🛴', name: 'kick scooter', keywords: ['scooter', 'ride', 'commute'] },
      { emoji: '🚲', name: 'bicycle', keywords: ['bike', 'cycling', 'pedal', 'green'] },
      { emoji: '🛵', name: 'motor scooter', keywords: ['vespa', 'moped', 'delivery'] },
      { emoji: '🏍️', name: 'motorcycle', keywords: ['motorbike', 'biker', 'speed'] },
      { emoji: '🛺', name: 'auto rickshaw', keywords: ['tuktuk', 'taxi', 'ride'] },
      { emoji: '🛞', name: 'wheel', keywords: ['tire', 'turn', 'drive'] },
      { emoji: '🚂', name: 'locomotive', keywords: ['train', 'steam', 'engine', 'rail'] },
      { emoji: '🚆', name: 'train', keywords: ['railway', 'commute', 'metro'] },
      { emoji: '🚇', name: 'metro', keywords: ['subway', 'underground', 'tube'] },
      { emoji: '🚊', name: 'tram', keywords: ['streetcar', 'trolley', 'light rail'] },
      { emoji: '🚁', name: 'helicopter', keywords: ['chopper', 'rotor', 'flight'] },
      { emoji: '✈️', name: 'airplane', keywords: ['flight', 'travel', 'plane', 'aviation'] },
      { emoji: '🛫', name: 'airplane departure', keywords: ['takeoff', 'flight', 'departure'] },
      { emoji: '🛬', name: 'airplane arrival', keywords: ['landing', 'arrival', 'trip'] },
      { emoji: '🪂', name: 'parachute', keywords: ['skydive', 'fall', 'safety'] },
      { emoji: '💺', name: 'seat', keywords: ['flight seat', 'chair', 'booked'] },
      { emoji: '🛰️', name: 'satellite', keywords: ['orbit', 'space', 'gps'] },
      { emoji: '🚀', name: 'rocket', keywords: ['launch', 'spaceship', 'fast', 'startup'] },
      { emoji: '🛸', name: 'flying saucer', keywords: ['ufo', 'alien', 'sci-fi'] },
      { emoji: '⛵', name: 'sailboat', keywords: ['boat', 'yacht', 'sailing', 'ocean'] },
      { emoji: '🚤', name: 'speedboat', keywords: ['motorboat', 'lake', 'water'] },
      { emoji: '🚢', name: 'ship', keywords: ['ocean', 'vessel', 'cargo'] },
      { emoji: '🛳️', name: 'passenger ship', keywords: ['cruise', 'vacation', 'ferry'] },
      { emoji: '⛴️', name: 'ferry', keywords: ['boat', 'commute', 'water'] },
      { emoji: '⚓', name: 'anchor', keywords: ['nautical', 'marine', 'harbor'] },
      { emoji: '⛽', name: 'fuel pump', keywords: ['gas', 'petrol', 'station', 'refuel'] },
      { emoji: '🚏', name: 'bus stop', keywords: ['transit', 'station', 'waiting'] },
      { emoji: '🚦', name: 'vertical traffic light', keywords: ['signals', 'stoplight', 'rules'] },
      { emoji: '🚥', name: 'horizontal traffic light', keywords: ['signals', 'traffic'] },
      { emoji: '🚧', name: 'construction', keywords: ['barrier', 'wip', 'roadwork'] },
      { emoji: '🛑', name: 'stop sign', keywords: ['halt', 'danger', 'road sign'] },
      { emoji: '🏠', name: 'house', keywords: ['home', 'residence', 'building'] },
      { emoji: '🏡', name: 'house with garden', keywords: ['home', 'suburbs', 'yard'] },
      { emoji: '🏢', name: 'office building', keywords: ['company', 'work', 'skyscraper', 'corp'] },
      { emoji: '🏬', name: 'department store', keywords: ['mall', 'shopping', 'store'] },
      { emoji: '🏣', name: 'japanese post office', keywords: ['post', 'mail'] },
      { emoji: '🏥', name: 'hospital', keywords: ['doctor', 'clinic', 'medical', 'emergency'] },
      { emoji: '🏦', name: 'bank', keywords: ['money', 'finance', 'deposit', 'building'] },
      { emoji: '🏨', name: 'hotel', keywords: ['stay', 'travel', 'room', 'resort'] },
      { emoji: '🏪', name: 'convenience store', keywords: ['7eleven', 'shop', 'groceries'] },
      { emoji: '🏫', name: 'school', keywords: ['education', 'building', 'classroom', 'student'] },
      { emoji: '🏛️', name: 'classical building', keywords: ['museum', 'capitol', 'government', 'monument'] },
      { emoji: '⛪', name: 'church', keywords: ['chapel', 'religion', 'building'] },
      { emoji: '🕌', name: 'mosque', keywords: ['islam', 'religion', 'building'] },
      { emoji: '🛕', name: 'hindu temple', keywords: ['mandir', 'temple', 'worship'] },
      { emoji: '🕍', name: 'synagogue', keywords: ['jewish', 'temple', 'worship'] },
      { emoji: '🏰', name: 'castle', keywords: ['fortress', 'palace', 'medieval'] },
      { emoji: '🏯', name: 'japanese castle', keywords: ['fortress', 'historic', 'pagoda'] },
      { emoji: '🏭', name: 'factory', keywords: ['industry', 'manufacturing', 'plant'] },
      { emoji: '🗼', name: 'tokyo tower', keywords: ['landmark', 'japan', 'tower'] },
      { emoji: '🗽', name: 'statue of liberty', keywords: ['new york', 'usa', 'landmark'] },
      { emoji: '🏟️', name: 'stadium', keywords: ['sports', 'arena', 'concert'] },
      { emoji: '⛺', name: 'tent', keywords: ['camping', 'camp', 'outdoors'] },
      { emoji: '🛖', name: 'hut', keywords: ['shelter', 'cabin', 'wood'] },
      { emoji: '🏙️', name: 'cityscape', keywords: ['skyline', 'city', 'urban', 'downtown'] },
      { emoji: '🌄', name: 'sunrise over mountains', keywords: ['morning', 'sun', 'peak'] },
      { emoji: '🌅', name: 'sunrise', keywords: ['dawn', 'morning', 'sun'] },
      { emoji: '🌆', name: 'cityscape at dusk', keywords: ['evening', 'sunset', 'city'] },
      { emoji: '🌇', name: 'sunset', keywords: ['dusk', 'evening', 'sun'] },
      { emoji: '🌉', name: 'bridge at night', keywords: ['bridge', 'crossing', 'bay'] },
      { emoji: '🌌', name: 'milky way', keywords: ['galaxy', 'space', 'stars', 'night'] },
      { emoji: '🌠', name: 'shooting star', keywords: ['wish', 'falling star', 'meteor'] },
      { emoji: '🎆', name: 'fireworks', keywords: ['celebrate', 'festival', 'new year'] },
      { emoji: '🎇', name: 'sparkler', keywords: ['celebration', 'firework', 'party'] },
      { emoji: '🗾', name: 'map of japan', keywords: ['island', 'geography', 'japan'] },
      { emoji: '🎑', name: 'moon viewing ceremony', keywords: ['harvest', 'japanese', 'moon'] },
      { emoji: '🏞️', name: 'national park', keywords: ['nature', 'mountain', 'lake'] },
      { emoji: '🌋', name: 'volcano', keywords: ['eruption', 'lava', 'mountain'] },
      { emoji: '🗻', name: 'mount fuji', keywords: ['mountain', 'japan', 'snow'] },
      { emoji: '🏔️', name: 'snow-capped mountain', keywords: ['mountain', 'alps', 'snow', 'cold'] },
      { emoji: '🏕️', name: 'camping', keywords: ['campsite', 'tent', 'nature'] },
      { emoji: '🏖️', name: 'beach with umbrella', keywords: ['sand', 'sea', 'vacation'] },
      { emoji: '🏜️', name: 'desert', keywords: ['sand', 'dry', 'dunes'] },
      { emoji: '🏝️', name: 'desert island', keywords: ['palm tree', 'beach', 'tropical'] },
      { emoji: '🌐', name: 'globe with meridians', keywords: ['internet', 'world', 'global', 'web'] },
      { emoji: '🗺️', name: 'world map', keywords: ['atlas', 'geography', 'travel', 'plan'] },
      { emoji: '🧭', name: 'compass', keywords: ['navigation', 'direction', 'explore', 'guide'] },
      { emoji: '🌍', name: 'globe showing europe-africa', keywords: ['earth', 'world', 'planet'] },
      { emoji: '🌎', name: 'globe showing americas', keywords: ['earth', 'world', 'planet'] },
      { emoji: '🌏', name: 'globe showing asia-australia', keywords: ['earth', 'world', 'planet'] },
      { emoji: '🧱', name: 'brick', keywords: ['wall', 'build', 'foundation'] },
      { emoji: '🪨', name: 'rock', keywords: ['stone', 'boulder', 'solid'] },
      { emoji: '🪵', name: 'wood', keywords: ['log', 'timber', 'nature'] },
      { emoji: '🛤️', name: 'railway track', keywords: ['train', 'journey', 'rails'] },
      { emoji: '🛣️', name: 'motorway', keywords: ['highway', 'road', 'trip'] },
      { emoji: '🛎️', name: 'bellhop bell', keywords: ['hotel', 'service', 'reception'] },
      { emoji: '🎡', name: 'ferris wheel', keywords: ['amusement park', 'fair', 'carnival'] },
      { emoji: '🎢', name: 'roller coaster', keywords: ['amusement park', 'thrill', 'ride'] },
      { emoji: '🎠', name: 'carousel horse', keywords: ['merry go round', 'ride'] },
    ],
  },
  {
    id: 'symbols',
    label: 'Symbols',
    icon: '⭐',
    emojis: [
      { emoji: '✅', name: 'check mark button', keywords: ['done', 'ok', 'complete', 'approve', 'green'] },
      { emoji: '❌', name: 'cross mark', keywords: ['cancel', 'delete', 'error', 'no', 'close'] },
      { emoji: '⭕', name: 'hollow red circle', keywords: ['circle', 'o', 'mark'] },
      { emoji: '🛑', name: 'octagonal sign', keywords: ['stop', 'halt', 'red'] },
      { emoji: '⛔', name: 'no entry', keywords: ['forbidden', 'denied', 'stop'] },
      { emoji: '🚫', name: 'prohibited', keywords: ['forbidden', 'no', 'restricted'] },
      { emoji: '⚠️', name: 'warning', keywords: ['caution', 'alert', 'danger', 'notice'] },
      { emoji: '🚸', name: 'children crossing', keywords: ['caution', 'safety', 'school'] },
      { emoji: '♻️', name: 'recycling symbol', keywords: ['recycle', 'green', 'environment', 'reuse'] },
      { emoji: '❇️', name: 'sparkle', keywords: ['star', 'clean', 'shine'] },
      { emoji: '✳️', name: 'eight-spoked asterisk', keywords: ['star', 'spark', 'asterisk'] },
      { emoji: '✴️', name: 'eight-pointed star', keywords: ['star', 'shine', 'glow'] },
      { emoji: '💠', name: 'diamond with a dot', keywords: ['gem', 'crystal', 'shape', 'kawaii'] },
      { emoji: '🔷', name: 'large blue diamond', keywords: ['shape', 'blue', 'geometric'] },
      { emoji: '🔶', name: 'large orange diamond', keywords: ['shape', 'orange', 'geometric'] },
      { emoji: '🔹', name: 'small blue diamond', keywords: ['shape', 'blue', 'bullet'] },
      { emoji: '🔸', name: 'small orange diamond', keywords: ['shape', 'orange', 'bullet'] },
      { emoji: '🔺', name: 'red triangle pointed up', keywords: ['up', 'triangle', 'arrow'] },
      { emoji: '🔻', name: 'red triangle pointed down', keywords: ['down', 'triangle', 'arrow'] },
      { emoji: '🔘', name: 'radio button', keywords: ['select', 'choice', 'input'] },
      { emoji: '🔳', name: 'white square button', keywords: ['square', 'frame', 'shape'] },
      { emoji: '🔲', name: 'black square button', keywords: ['square', 'frame', 'dark'] },
      { emoji: '🏁', name: 'chequered flag', keywords: ['finish', 'race', 'winner', 'completed'] },
      { emoji: '🚩', name: 'triangular flag', keywords: ['red flag', 'milestone', 'marker', 'goal'] },
      { emoji: '🎌', name: 'crossed flags', keywords: ['celebration', 'flags', 'japan'] },
      { emoji: '🏴', name: 'black flag', keywords: ['flag', 'dark', 'marker'] },
      { emoji: '🏳️', name: 'white flag', keywords: ['peace', 'surrender', 'flag'] },
      { emoji: '💬', name: 'speech balloon', keywords: ['comment', 'chat', 'message', 'dialog'] },
      { emoji: '👁️‍🗨️', name: 'eye in speech bubble', keywords: ['witness', 'look', 'notice'] },
      { emoji: '🗨️', name: 'left speech bubble', keywords: ['talk', 'dialogue', 'chat'] },
      { emoji: '🗯️', name: 'right anger bubble', keywords: ['shout', 'angry', 'yell'] },
      { emoji: '💭', name: 'thought balloon', keywords: ['thinking', 'idea', 'dream'] },
      { emoji: '💤', name: 'zzz', keywords: ['sleep', 'tired', 'bored'] },
      { emoji: '💥', name: 'collision', keywords: ['boom', 'blast', 'bang', 'impact'] },
      { emoji: '💫', name: 'dizzy', keywords: ['star', 'sparkle', 'magic'] },
      { emoji: '💦', name: 'sweat droplets', keywords: ['water', 'work', 'sweat'] },
      { emoji: '💨', name: 'dashing away', keywords: ['fast', 'speed', 'rush', 'wind'] },
      { emoji: '🔥', name: 'fire', keywords: ['hot', 'flame', 'streak', 'lit', 'popular'] },
      { emoji: '⚡', name: 'high voltage', keywords: ['lightning', 'zap', 'fast', 'quick', 'energy'] },
      { emoji: '✨', name: 'sparkles', keywords: ['magic', 'shine', 'clean', 'new', 'star', 'ai'] },
      { emoji: '🌟', name: 'glowing star', keywords: ['star', 'shiny', 'winner', 'bright'] },
      { emoji: '⭐️', name: 'star', keywords: ['favorite', 'priority', 'bookmark', 'rate'] },
      { emoji: '☄️', name: 'comet', keywords: ['space', 'meteor', 'fast'] },
      { emoji: '☀️', name: 'sun', keywords: ['sunny', 'weather', 'bright', 'day'] },
      { emoji: '🌤️', name: 'sun behind small cloud', keywords: ['partly cloudy', 'weather'] },
      { emoji: '⛅', name: 'sun behind cloud', keywords: ['cloudy', 'weather', 'sun'] },
      { emoji: '🌥️', name: 'sun behind large cloud', keywords: ['overcast', 'weather'] },
      { emoji: '☁️', name: 'cloud', keywords: ['weather', 'overcast', 'sky'] },
      { emoji: '🌧️', name: 'cloud with rain', keywords: ['rain', 'weather', 'storm'] },
      { emoji: '⛈️', name: 'cloud with lightning and rain', keywords: ['thunderstorm', 'storm'] },
      { emoji: '🌩️', name: 'cloud with lightning', keywords: ['lightning', 'storm', 'weather'] },
      { emoji: '🌨️', name: 'cloud with snow', keywords: ['snow', 'winter', 'weather'] },
      { emoji: '❄️', name: 'snowflake', keywords: ['cold', 'winter', 'ice', 'freeze'] },
      { emoji: '☃️', name: 'snowman with snow', keywords: ['winter', 'holiday', 'cold'] },
      { emoji: '⛄', name: 'snowman without snow', keywords: ['winter', 'cold'] },
      { emoji: '🌬️', name: 'wind face', keywords: ['breeze', 'blow', 'weather'] },
      { emoji: '💧', name: 'droplet', keywords: ['water', 'tear', 'liquid', 'drop'] },
      { emoji: '🌊', name: 'water wave', keywords: ['ocean', 'sea', 'surf', 'tsunami'] },
      { emoji: '🌈', name: 'rainbow', keywords: ['colors', 'pride', 'sky', 'nature'] },
      { emoji: '☂️', name: 'umbrella', keywords: ['rain', 'protection', 'weather'] },
      { emoji: '☔', name: 'umbrella with rain drops', keywords: ['rain', 'storm', 'wet'] },
      { emoji: '❤️', name: 'red heart', keywords: ['love', 'like', 'favorite', 'heart'] },
      { emoji: '🧡', name: 'orange heart', keywords: ['warm', 'love', 'heart'] },
      { emoji: '💛', name: 'yellow heart', keywords: ['friendship', 'gold', 'heart'] },
      { emoji: '💚', name: 'green heart', keywords: ['eco', 'nature', 'health', 'heart'] },
      { emoji: '💙', name: 'blue heart', keywords: ['trust', 'calm', 'heart'] },
      { emoji: '💜', name: 'purple heart', keywords: ['magic', 'royalty', 'heart'] },
      { emoji: '🖤', name: 'black heart', keywords: ['dark', 'goth', 'heart'] },
      { emoji: '🤍', name: 'white heart', keywords: ['pure', 'peace', 'heart'] },
      { emoji: '🤎', name: 'brown heart', keywords: ['earth', 'coffee', 'heart'] },
      { emoji: '💔', name: 'broken heart', keywords: ['heartbreak', 'sad', 'breakup'] },
      { emoji: '❣️', name: 'heart exclamation', keywords: ['love', 'emphasis', 'heart'] },
      { emoji: '💕', name: 'two hearts', keywords: ['love', 'sweet', 'hearts'] },
      { emoji: '💞', name: 'revolving hearts', keywords: ['love', 'motion', 'affection'] },
      { emoji: '💓', name: 'beating heart', keywords: ['pulse', 'heartbeat', 'alive'] },
      { emoji: '💗', name: 'growing heart', keywords: ['excitement', 'love', 'heart'] },
      { emoji: '💖', name: 'sparkling heart', keywords: ['shine', 'love', 'special'] },
      { emoji: '💘', name: 'heart with arrow', keywords: ['cupid', 'love', 'crush'] },
      { emoji: '💝', name: 'heart with ribbon', keywords: ['gift', 'present', 'love'] },
      { emoji: '💟', name: 'heart decoration', keywords: ['purple', 'frame', 'heart'] },
      { emoji: '☯️', name: 'yin yang', keywords: ['balance', 'harmony', 'zen'] },
      { emoji: '☮️', name: 'peace symbol', keywords: ['peace', 'harmony', 'calm'] },
      { emoji: '✝️', name: 'latin cross', keywords: ['religion', 'christian', 'cross'] },
      { emoji: '☪️', name: 'star and crescent', keywords: ['islam', 'muslim', 'religion'] },
      { emoji: '☸️', name: 'wheel of dharma', keywords: ['buddhism', 'dharma', 'religion'] },
      { emoji: '✡️', name: 'star of david', keywords: ['judaism', 'jewish', 'religion'] },
      { emoji: '🔯', name: 'dotted six-pointed star', keywords: ['star', 'hexagram'] },
      { emoji: '🕎', name: 'menorah', keywords: ['hanukkah', 'candles', 'judaism'] },
      { emoji: '♾️', name: 'infinity', keywords: ['forever', 'endless', 'loop'] },
      { emoji: '🆔', name: 'ID button', keywords: ['identifier', 'identity', 'badge'] },
      { emoji: '🆕', name: 'NEW button', keywords: ['fresh', 'new', 'update', 'badge'] },
      { emoji: '🆙', name: 'UP! button', keywords: ['level up', 'upgrade', 'up'] },
      { emoji: '🆒', name: 'COOL button', keywords: ['awesome', 'badge', 'tag'] },
      { emoji: '🆓', name: 'FREE button', keywords: ['gratis', 'zero', 'badge'] },
      { emoji: '🔢', name: 'input numbers', keywords: ['1234', 'digits', 'math', 'keypad'] },
      { emoji: '🔣', name: 'input symbols', keywords: ['symbols', 'special characters'] },
      { emoji: '🔤', name: 'input latin letters', keywords: ['abc', 'alphabet', 'font'] },
    ],
  },
];
