export const IPC = {
  APP: {
    GET_STARTUP_DATA: 'app:get-startup-data',
    GET_INFO: 'app:get-info',
    MINIMIZE: 'app:minimize',
    MAXIMIZE: 'app:maximize',
    CLOSE: 'app:close',
    QUIT: 'app:quit',
    TRIM_MEMORY: 'app:trim-memory',
    SET_ALWAYS_ON_TOP: 'app:set-always-on-top',
    GET_ALWAYS_ON_TOP: 'app:get-always-on-top',
    SET_OPACITY: 'app:set-opacity',
    SHOW_OMNIBAR: 'app:show-omnibar',
    HIDE_OMNIBAR: 'app:hide-omnibar',
    FOCUS_QUICK_ADD: 'app:focus-quick-add',
    CHECK_FOR_UPDATES: 'app:check-for-updates',
    UPDATE_AVAILABLE: 'app:update-available',
    UPDATE_DOWNLOADED: 'app:update-downloaded',
  },
  SYSTEM: {
    GET_INFO: 'system:get-info',
    MINIMIZE: 'system:minimize',
    MAXIMIZE: 'system:maximize',
    CLOSE: 'system:close',
  },
  TASKS: {
    GET_ALL: 'tasks:get-all',
    GET_BY_ID: 'tasks:get-by-id',
    GET_BY_LIST: 'tasks:get-by-list',
    CREATE: 'tasks:create',
    UPDATE: 'tasks:update',
    DELETE: 'tasks:delete',
    RESTORE: 'tasks:restore',
    TOGGLE_COMPLETE: 'tasks:toggle-complete',
    STAR: 'tasks:star',
    UNSTAR: 'tasks:unstar',
    DUPLICATE: 'tasks:duplicate',
    MAKE_SUBTASK: 'tasks:make-subtask',
    PROMOTE_SUBTASK: 'tasks:promote-subtask',
    GET_SUBTASKS: 'tasks:get-subtasks',
    GET_MY_DAY: 'tasks:get-my-day',
    GET_IMPORTANT: 'tasks:get-important',
    GET_PLANNED: 'tasks:get-planned',
    GET_COMPLETED: 'tasks:get-completed',
    ADD_TO_MY_DAY: 'tasks:add-to-my-day',
    REMOVE_FROM_MY_DAY: 'tasks:remove-from-my-day',
    REORDER: 'tasks:reorder',
    BATCH_UPDATE: 'tasks:batch-update',
  },
  LISTS: {
    GET_ALL: 'lists:get-all',
    GET_BY_ID: 'lists:get-by-id',
    CREATE: 'lists:create',
    UPDATE: 'lists:update',
    DELETE: 'lists:delete',
    REORDER: 'lists:reorder',
  },
  LIST_GROUPS: {
    GET_ALL: 'list-groups:get-all',
    CREATE: 'list-groups:create',
    UPDATE: 'list-groups:update',
    DELETE: 'list-groups:delete',
    REORDER: 'list-groups:reorder',
  },
  PROJECTS: {
    GET_ALL: 'projects:get-all',
    GET_BY_ID: 'projects:get-by-id',
    CREATE: 'projects:create',
    UPDATE: 'projects:update',
    DELETE: 'projects:delete',
    REORDER: 'projects:reorder',
  },
  SECTIONS: {
    GET_ALL: 'sections:get-all',
    CREATE: 'sections:create',
    UPDATE: 'sections:update',
    DELETE: 'sections:delete',
    REORDER: 'sections:reorder',
  },
  TAGS: {
    GET_ALL: 'tags:get-all',
    CREATE: 'tags:create',
    UPDATE: 'tags:update',
    DELETE: 'tags:delete',
  },
  REMINDERS: {
    GET_ALL: 'reminders:get-all',
    SET: 'reminders:set',
    DISMISS: 'reminders:dismiss',
    SNOOZE: 'reminders:snooze',
  },
  ATTACHMENTS: {
    GET_ALL: 'attachments:get-all',
    ADD: 'attachments:add',
    DELETE: 'attachments:delete',
    OPEN: 'attachments:open',
  },
  POMODORO: {
    START: 'pomodoro:start',
    PAUSE: 'pomodoro:pause',
    STOP: 'pomodoro:stop',
    GET_TODAY_STATS: 'pomodoro:get-today-stats',
    GET_SESSIONS: 'pomodoro:get-sessions',
  },
  GOALS: {
    GET_ALL: 'goals:get-all',
    GET_BY_ID: 'goals:get-by-id',
    CREATE: 'goals:create',
    UPDATE: 'goals:update',
    DELETE: 'goals:delete',
    LINK_TASK: 'goals:link-task',
  },
  SETTINGS: {
    GET_ALL: 'settings:get-all',
    GET: 'settings:get',
    SET: 'settings:set',
    RESET: 'settings:reset',
    THEME_CHANGED: 'settings:theme-changed',
    ACCENT_COLOR_CHANGED: 'settings:accent-color-changed',
  },
  MODULES: {
    GET_ALL: 'modules:get-all',
    SET_ACTIVE: 'modules:set-active',
  },
  SEARCH: {
    QUERY: 'search:query',
    REINDEX: 'search:reindex',
  },
  NOTIFICATIONS: {
    GET_HISTORY: 'notifications:get-history',
    CLEAR: 'notifications:clear',
    SEND_NATIVE: 'notifications:send-native',
  },
  IDENTITY: {
    GET: 'identity:get',
    UPDATE: 'identity:update',
  },
  SYNC: {
    GET_STATUS: 'sync:get-status',
    PAIR_DEVICE: 'sync:pair-device',
    QUEUE_CHANGE: 'sync:queue-change',
  },
} as const;

export type IpcChannelGroup = keyof typeof IPC;
