import { registerAppHandlers } from './app-handlers.js';
import { registerTaskHandlers } from './task-handlers.js';
import { registerListHandlers } from './list-handlers.js';
import { registerListGroupHandlers } from './list-group-handlers.js';
import { registerProjectHandlers } from './project-handlers.js';
import { registerSectionHandlers } from './section-handlers.js';
import { registerMilestoneHandlers } from './milestone-handlers.js';
import { registerDependencyHandlers } from './dependency-handlers.js';
import { registerTagHandlers } from './tag-handlers.js';
import { registerReminderHandlers } from './reminder-handlers.js';
import { registerAttachmentHandlers } from './attachment-handlers.js';
import { registerPomodoroHandlers } from './pomodoro-handlers.js';
import { registerGoalHandlers } from './goal-handlers.js';
import { registerSettingsHandlers } from './settings-handlers.js';
import { registerModuleHandlers } from './module-handlers.js';
import { registerSearchHandlers } from './search-handlers.js';
import { registerNotificationHandlers } from './notification-handlers.js';
import { registerIdentityHandlers } from './identity-handlers.js';
import { registerNlpHandlers } from './nlp-handlers.js';
import { registerCalendarHandlers } from './calendar-handlers.js';
import { registerAnalyticsHandlers } from './analytics-handlers.js';
import { registerSecurityHandlers } from './security-handlers.js';
import { registerExportHandlers } from './export-handlers.js';
import { registerImportHandlers } from './import-handlers.js';
import { registerBackupHandlers } from './backup-handlers.js';

export function registerIpcHandlers(): void {
  registerAppHandlers();
  registerTaskHandlers();
  registerListHandlers();
  registerListGroupHandlers();
  registerProjectHandlers();
  registerSectionHandlers();
  registerMilestoneHandlers();
  registerDependencyHandlers();
  registerTagHandlers();
  registerReminderHandlers();
  registerAttachmentHandlers();
  registerPomodoroHandlers();
  registerGoalHandlers();
  registerSettingsHandlers();
  registerModuleHandlers();
  registerSearchHandlers();
  registerNotificationHandlers();
  registerIdentityHandlers();
  registerNlpHandlers();
  registerCalendarHandlers();
  registerAnalyticsHandlers();
  registerSecurityHandlers();
  registerExportHandlers();
  registerImportHandlers();
  registerBackupHandlers();
}

export default registerIpcHandlers;
